
let value = 3 ;

let negvalue = -value ;
console.log (negvalue)

console.log (2+2) ;
console.log (2-2) ;
console.log (2*2) ;
console.log (2**3) ;
console.log (2%3) ;
console.log (2/3) ;

let str1 = "Hello" ;

let str2 = " Ali Yahya" ;
 let str3 = str1 + str2 ;
 
console.log(str3)

console.log ("1" + 2 + 3)

// agr string pehly ayia ga to phr concat hu ga
// agr string baad ma ayia ga to pehly wali pehly add hu ga phr concat hu ga

let num1 , num2 , num3 ;
 num1 = num2 = num3 = 2 +2 ;


console.log(1 + 2 + "3")

let i = 3 ;
 let j = i++ ;
  console.log( ` i : ${i} , j : ${j}`)

  /**************    ++++++   ***********/

/*If used postfix, with operator after operand (for example, x++), the increment operator increments and returns the value before incrementing.

If used prefix, with operator before operand (for example, ++x), the increment operator increments and returns the value after incrementing.*/











